/*
=============================================================
IslamIQ Sales Analysis
SQL Analytics Queries
Author: Amr Ahmed

This file contains analytical SQL queries used to explore sales,
customers, and product performance for the IslamIQ e-commerce dataset.

Tables used:
- customers
- products
- orders
- order_items

The queries focus on common business analytics questions such as revenue
performance, product demand, customer behavior, and acquisition sources.

Each section includes:
• Business question
• SQL query used to answer it
• Result interpretation (added after execution)
=============================================================
*/

/* Business Question:
What is the total revenue generated by the store?
*/

SELECT
	ROUND(SUM(order_total), 2) AS total_revenue
FROM orders
WHERE order_status = 'completed';

/* Insight:
The revenue generated by the completed orders in this dataset
was $136,609.35.
This value represents the total realized sales after discounts,
taxes, and shipping adjustments for all completed transactions.
*/

-- =============================================================

/* Business Question:
What is the average order value (AOV)?
*/

SELECT
	ROUND(AVG(order_total), 2) AS avg_order_value
FROM orders
WHERE order_status = 'completed';

/* Insight:
IslamIQ's customers tend to pay an average of $173.80
per order - after discounts, shipping, and taxes.
*/

-- =============================================================

/* Business Question:
Which product generates the most gross profit?
*/

SELECT p.product_id, p.product_name,
	SUM(oi.quantity) AS quantity_sold, 
    ROUND(SUM(oi.quantity * oi.price), 2) AS gross_revenue,
    ROUND(SUM(oi.quantity * p.cost), 2) AS total_cost,
    ROUND(SUM(oi.quantity * (oi.price - p.cost)), 2) AS gross_profit
FROM products p
JOIN order_items oi
	ON p.product_id = oi.product_id
JOIN orders o
	ON oi.order_id = o.order_id
WHERE o.order_status = 'completed'
GROUP BY p.product_id, p.product_name
ORDER BY gross_profit DESC;

/* Insight:
IslamIQ's highest-gross-profit products were the 4 variations of the 
Family Tree of Prophet Muhammad, with the Arabic version in the wooden
frame as the lead product.
NOTE: there were products with higher 'quantity_sold', but it is clear
that does not always equate to what is the most profitable.
*/

-- =============================================================

/* Business Question:
Which products are purchased most frequently?
*/

SELECT p.product_id, p.product_name,
	SUM(o.quantity) AS quantity_sold
FROM order_items o
JOIN products p
	ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY quantity_sold DESC
LIMIT 3;

/* Insight:
This shows us that despite none of these products were in the list of
the highest-grossing-profit products, these are still the most popular
products as they are the most frequently purchased.
*/

-- =============================================================

/* Business Question:
Which product categories generate the most gross profit?
*/

SELECT p.category,
	ROUND(SUM(o.quantity * (o.price - p.cost)), 2) AS gross_profit
FROM order_items o
JOIN products p
	ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY gross_profit DESC;

/* Insight:
It's clear that Wall Art is IslamIQ's biggest gross-profit generating category,
at $66k as opposed to apparel, which is next in line at 10% of that amount.
This indicates that Wall Art is the category generating the largest share of
customer spending.
*/

-- =============================================================

/* Business Question:
Which product categories perform best by revenue, profit, and margin?
*/

SELECT p.category,
	ROUND(SUM(o.quantity * o.price), 2) AS gross_revenue,
    ROUND(SUM(o.quantity * p.cost), 2) AS total_cost,
    ROUND(SUM(o.quantity * (o.price - p.cost)), 2) AS gross_profit,
    ROUND(SUM(o.quantity * (o.price - p.cost)) / NULLIF(SUM(o.quantity * o.price), 0), 2) AS margin_percent
FROM order_items o
JOIN products p
	ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY margin_percent DESC;

/* Insight:
Here we can see that the data is slightly skewed due to Digital Downloads
showing as having 'no costs'. This is mostly true, except that Square still
does take a percentage of each transaction as with all other categories. We
still can conclude that Wall Art grosses both the highest revenue and profit
by far, and sits at a decent margin of 44% (pre discounts+taxes). Also, whatever
is in 'other' needs to go. 19% margins mean our efforts are best spent elsewhere.
*/

-- =============================================================

/* Business Question:
How have revenue and profit changed over time?
*/

SELECT
	DATE_FORMAT(o.order_date, '%Y/%m') AS 'month',
    ROUND(SUM(oi.quantity * oi.price), 2) AS revenue,
    ROUND(SUM(oi.quantity * p.cost), 2) AS total_cost,
    ROUND(SUM(oi.quantity * (oi.price - p.cost)), 2) AS profit
FROM orders o
JOIN order_items oi
	ON o.order_id = oi.order_id
JOIN products p
	ON oi.product_id = p.product_id
WHERE o.order_status = 'completed'
GROUP BY DATE_FORMAT(o.order_date, '%Y/%m')
ORDER BY DATE_FORMAT(o.order_date, '%Y/%m') ASC;

/* Insight:
This shows us IslamIQ's monthly revenue, COGS, and profit per month for 12
months. It's clear there hasn't been much change in profit as it oscillates within
a small range, although at the end, it seems that there was approximately a 20%
dip in profits. 2026/03 is only a third of the month, although seems to be following
similar flow to the month before. Overall - no growth.
*/

-- =============================================================

/* Business Question:
Which sign-up sources bring in the most customers and revenue?
*/

SELECT 
	CASE
		WHEN c.signup_source IS NULL or c.signup_source = '' THEN 'Other'
        ELSE c.signup_source
	END AS signup_source,
COUNT(DISTINCT c.customer_id) AS customers_acquired,
ROUND(SUM(o.order_total), 2) AS total_revenue
FROM customers c
JOIN orders o
	ON c.customer_id = o.customer_id
WHERE o.order_status = 'completed'
GROUP BY
	CASE
		WHEN c.signup_source IS NULL or c.signup_source = '' THEN 'Other'
        ELSE c.signup_source
	END
ORDER BY total_revenue DESC;

/* Insight:
This shows us that more people signed up during checkout (391) as opposed to
those who actually signed up for a discount code (254). This may signal something
about the lack of price-sensitivity of a large portion of customers, or it may
mean that discounts are not promoted as strongly. Majority of total revenue
collected from customers who did not use a discount code.
*/

-- =============================================================

/* Business Question:
Which regions generate the strongest sales performance?
*/

SELECT c.city, c.country,
	COUNT(DISTINCT o.order_id) AS total_orders,
	ROUND(SUM(o.order_total), 2) AS total_revenue,
	ROUND(AVG(o.order_total), 2) AS aov,
    ROUND(SUM(SUM(o.order_total)) OVER (PARTITION BY c.country), 2) AS country_total_revenue,
    ROUND(SUM(o.order_total) / SUM(SUM(o.order_total)) OVER (PARTITION BY c.country) * 100, 2) AS portion_of_country_total
FROM customers c
JOIN orders o
	ON c.customer_id = o.customer_id
WHERE order_status = 'completed'
GROUP BY c.city, c.country
ORDER BY country_total_revenue DESC, total_revenue DESC;

/* Insight:
This query ranks countries from highest to lowest based on total revenue generated
from each country, telling us the total amount, and further breaking it down by city,
telling us, in order, how much revenue is generated per city. 
*/

-- =============================================================

/* Business Question:
How much revenue is being reduced by discounts, and do discounts affect AOV?
*/

SELECT 
	CASE
		WHEN discount_code IS NULL OR discount_code = '' THEN 'no discount'
        ELSE discount_code
	END AS discount_code,
    COUNT(order_id) AS number_of_uses,
    ROUND(SUM(order_total), 2) AS total_revenue,
    ROUND(AVG(order_total), 2) AS AOV,
    ROUND(SUM(discount_amount), 2) AS total_discount_given
FROM orders
WHERE order_status = 'completed'
GROUP BY CASE
			WHEN discount_code IS NULL OR discount_code = '' THEN 'no discount'
			ELSE discount_code
		END
ORDER BY total_discount_given DESC;

/* Insight:
Most revenue ($88,192) came from full-price orders, indicating strong
organic demand without reliance on discounts. WEB10 (10%) was the most frequently
used discount, with WEB15 (15%) after. AOV of more than 15% less than AOV of WEB10
orders indicates that customers who used WEB15 were more price-sensitive. 
Highest AOV came from 15% discounts given in person, suggesting that real life events
produce higher-intent customers, or increase engagement/trust factor.
*/

-- =============================================================

/* Business Question:
Which products generate the most revenue and profit?
*/

SELECT p.product_id, p.product_name,
	SUM(oi.quantity) AS units_sold,
	ROUND(SUM(oi.quantity * oi.price), 2) AS total_revenue,
    ROUND(SUM(oi.quantity * p.cost), 2) AS COGS,
    ROUND(SUM(oi.quantity * (oi.price - p.cost)), 2) AS gross_profit,
    ROUND(SUM(oi.quantity * (oi.price - p.cost)) / NULLIF(SUM(oi.quantity * oi.price), 0) * 100, 2) AS profit_margin
FROM products p
JOIN order_items oi
	ON p.product_id = oi.product_id
JOIN orders o
	ON oi.order_id = o.order_id
WHERE order_status = 'completed'
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;

/* Insights:
It's clear here that IslamIQ's highest revenue generators, as well as its
highest profit generators are the Family Tree of the Prophet in all its
variations. This shows solid demand, and healthy margins as opposed to other
products in their catalogue. But if we order by profit margin, we find that
unframed 24x36" posters have the highest margins (65%) apart from obvious
digital downloads.
*/